### ISSUE TITLE
BYG, JEI and Waila Harvestability Incompatibilities 

### ISSUE THREAD

**Issue by RobertHDPotatoes** [IchHabeHunger54/PropertyModifier#1]
Minecraft Version: 1.16.5
Forge Version: 36.2.2
Property Modifier Version: 1.16.5-0.5.5

Currently there is not proper compatibility between Property Modifier and the following three mods: Oh The Biomes You'll Go, Tool Stats, and Just Enough Items. The incompatibilities are as follows: 

Oh The Biomes You'll Go: You cannot change the harvest level of the blocks: "byg:budding_ametrine_ore", "byg:pendorite_ore", and "byg:pendorite_ore". If you change them to require harvest level 5, it simply does nothing. This may be the case for all blocks in the mod but I have only tested those three.

Tool Stats: Does not show modified harvest levels in the tooltips, it will only show vanilla values. For example, if you install Tool Stats, then change an Iron Pickaxe to have harvest level 5 in Property Modifier, it will still show that Iron Pickaxes have a harvest level of 2, even though they have a harvest level of 5 in game. Waila Harvestability has a similar issue if you enable the "Harvestability Tooltip" option in the config.

Just Enough Items: If you add a repair material it does not show up as a valid repair item in the Just Enough Items menu. For example, if you add iron nuggets as a repair material for chainmail armor, then right click on any piece of chainmail armor in the JEI menu and scroll through the Anvil options, iron nuggets do not show up as a valid repair item even though they can be used to repair chainmail in game.

**Comment by IchHabeHunger54** [comment]
Ok, status on this:

BYG: The harvest level for most ores is hardcoded. Ask BYG's mod author to include a config option. There is nothing I can do about that.

JEI: It is on JEI's side. I'll see what I can do, but this needs understanding JEI's code and then PRing the fix. Will take some time, and I can't promise it'll ever happen.

WAILA Harvestability: I'm a little confused, as you mentioned it in the title, but not in the issue. As far as I can tell, WAILA Harvestability should be working just fine.

Tool Stats: That's on both ends, I would say. Since I exactly know the issue, I'm gonna bug the author myself.

**Comment by RobertHDPotatoes** [comment]
I figured BYG would be a problem, I hear about a lot of issues with it due to hardcoding. For now I'll forget about it, thanks for trying. Also apologies about WAILA Harvestability, I should have included more details about that. There is a couple of issues:

WAILA screen tooltip doesn't adjust if an item is currently harvestable or not, if you go into config/waila/waila_plugins, then:

"currentlyharvestable": true >>> If you set a Stone Pickaxe to harvest level 5 in Property Modifier with this config option set to true, when looking at Diamond Ore it will still show it is not harvestable with a red "x" icon, and the harvest level of Diamond Ore (2) turning red. This is incorrect, because the stone pickaxe has a harvest level of 5 through Property Modifier, and is a visual bug.


Harvest Level Tooltips (for items) don't adjust with Property Modifier, if you go into config/wailaharvestability-client, then:

"harvest level tooltip": = true >>> If you set this config option to true, item tooltips will display their harvest level (example: Stone Pickaxe will say "Harvest Level :1" in the items tooltip). However, if you set a Stone Pickaxe to harvest level 5 through Property Modifier, the item tooltip from WAILA Harvestability will still simply still say: "Harvest Level :1" for the Stone Pickaxe, which again is false and just visually incorrect as the stone pickaxe actually does have a harvest level of 5.


I was really hoping since all these issues seemed similar that they would be a singular issue but I guess not, didn't mean to trouble you so much, sorry!

**Comment by IchHabeHunger54** [comment]
Newer versions have the fix for JEI. Won't be backported because it's not possible.
