### ISSUE TITLE
Ability to move items to groups by tags

### ISSUE THREAD

**Issue by Pipsqueak737** [IchHabeHunger54/PropertyModifier#10]
When moving a large number of similar items to a new item group, it can be a bit overwhelming. It would be nice if item tags were supported to make this a bit easier.

**Comment by IchHabeHunger54** [comment]
The changes in this mod are applied during startup, when no tags are available. Therefore, supporting tags is impossible.
However, you can use regex (regular expressions). Google is better at explaining the details than I am, but it essentially boils down to doing things like `.*_planks` to modify all planks at once.

**Comment by Pipsqueak737** [comment]
I didn't realize this mod supported regex, thanks!
