### ISSUE TITLE
I don't understand how to use this mod

### ISSUE THREAD

**Issue by Dekkii0** [IchHabeHunger54/PropertyModifier#14]
Hello, i tried using your mod on aternos , i modified the config file 
[minecraft:netherite_sword]
		#Sets the efficiency. Does not work for swords and tridents.
		efficiency = []
		#Sets the attack damage.
		attack_damage = [14]
		#Sets the attack speed.
		attack_speed = [1.7]
		#Sets the tool harvest level. Does not work for swords and tridents.
		harvest_level = []
And it keep crashing my serv , could you explain how to use the mod

**Comment by IchHabeHunger54** [comment]
What you were doing is wrong. It would be best to join the discord (https://discord.gg/GM6XSqM), which is where I prefer giving support - GitHub should be used for bugs only.
