### ISSUE TITLE
1.18.1 Version Crashes on Game Startup. (No Crashlog Link, Exit code: 0)

### ISSUE THREAD

**Issue by AlexTheSuprWolf** [IchHabeHunger54/PropertyModifier#4]
Game Crashes on Startup. Gives an "Exit Code: 0" error instead of an actual crash log.

I've provided the Latest.log file from the logs folder below. No idea if it helps or not.

[latest.log](https://github.com/IchHabeHunger54/PropertyModifier/files/7800053/latest.log)

**Comment by IchHabeHunger54** [comment]
Fixed with v0.1.1.
