### ISSUE TITLE
Can not Sets the repair material of the item. 

### ISSUE THREAD

**Issue by blood789** [IchHabeHunger54/PropertyModifier#6]
I write as this :

repair_material = ["minecraft:shield;minecraft:iron_ingot"]

But it doesn't work. The repair material of the shield also the palnk ， no change to iron_ingot.

**Comment by IchHabeHunger54** [comment]
Shields and elytras have a separate method of setting their repair materials, it is done via the item tags propertymodifier:shield_repair_material and propertymodifier:elytra_repair_material, respectively. I should probably outline this in the config.

**Comment by blood789** [comment]
Can you give a full example ? How to write to setting their repair materials.

You mean, can the current version be modified? Or, the current version cannot be modified, waiting for you to update?

If the current version can be modified, what is the complete writing format ？

Thanks.

**Comment by FastBoye127** [comment]
Seconding the above. I'm having the same difficulty. Can you provide an example of the correct syntax?
