### ISSUE TITLE
Harvest Level Does Not Work Correctly

### ISSUE THREAD

**Issue by RobertHDPotatoes** [IchHabeHunger54/PropertyModifier#7]
Issue: When you change any pickaxes harvest level through Property Modifier, it seems to make the pickaxe no longer able to harvest certain blocks at all. For example, if you change a stone pickaxe to have harvest level 3, you can mine Diamond Ore, however Cobblestone Stairs, Mossy Cobblestone Stairs, or really any stair variant (Including Wood!) Is no longer harvestable with that pickaxe. This is the same for wall variants, but slabs and blocks drop just fine, for some reason.

Expected: I expect to be able to harvest stair/wall variants with a pickaxe that has a harvest level of 3.

Minecraft Version: 1.16.5
Forge Version: 36.2.23
Property Modifier Version: 0.6.3

Video showing the bug, only thing changed is a stone pickaxe to have harvest level 3: 
https://www.youtube.com/watch?v=A36vI4BjA4A

**Comment by IchHabeHunger54** [comment]
Fixed as of v0.6.4, should be approved on CurseForge any moment.

**Comment by RobertHDPotatoes** [comment]
Thank you so much! Really appreciate the fix, works perfectly now.
